Homework Profiling
UsernameAlexei/PythonHW pull request #2
Opened 2021-06-07 23:57 UTC by UsernameAlexei

2021-06-08 16:15 UTC, arybin93 requested changes
Thank you for your work. I've left comments, please consider and resolve them

2021-06-08 16:15 UTC, arybin93 commented on Profiling_task.py
> +    return arr
Could you please add implementation by using `sorted` method or `sort` method for the list to your analysis?
Using `pandas` methods for sorting also interesting.

2021-06-08 16:15 UTC, arybin93 commented on Profiling_task.py
> +    up_1 = " ".join(" ".join(L) for L in un_list)
It will work only for a list with string values? How about a more general approach?

2021-06-08 16:15 UTC, arybin93 commented on Profiling_test_task.py
> +import unittest
Try to use pytest as well, you will like it

2021-06-08 16:15 UTC, arybin93 commented on Profiling_task_memory output.txt
> +C:\ProgramData\Anaconda3\python.exe "C:/Users/Алексей/Desktop/EPAM/EPAM Python stage 2/Profiling/Profiling_task_memory.py"
Please provide an analysis of your results. Try to explain why we got these results. Which implementation is best and why?

2021-06-16 11:47 UTC, arybin93 approved these changes
Good work. Accepted. 👍

2021-06-16 16:20 UTC, UsernameAlexei commented
Thank you

2022-08-08 23:25 UTC, merged